baseURL = "http://blog-ja.dtan4.net/"
languageCode = "en-us"
title = "blog-ja.dtan4.net"
theme = "anubis"

[author]
  name = "dtan4"

[menu]
  [[menu.main]]
    identifier = "archive"
    name = "Archive"
    title = "Archive"
    url = "/posts"
    weight = 0
