baseURL = "https://blog-ja.dtan4.net/"
languageCode = "ja-JP"
title = "blog-ja.dtan4.net"

theme = "hugo_theme_pickles"
copyright = "Copyright &copy; 2020 dtan4 All Rights Reserved"

[params]
twitter = "dtan4"
github = "dtan4"
author = "dtan4"
bio = "Software Engineer, Microservices Platform @ Tokyo, Japan"

[menu]
[[menu.main]]
name = "Blog"
url = "/"
weight = 0
