version: "3.4"

x-hugo-common:
  &hugo-common
  build: .
  working_dir: "/app"
  volumes:
    - "$PWD:/app"

services:
  hugo:
    << : *hugo-common

  hugo-server:
    << : *hugo-common
    ports:
      - "1313:1313"
    command:
      - "server"
      - "-D"
      - "--bind"
      - "0.0.0.0"
