#!/bin/bash

main() {
  set -eu
  set -o pipefail

  local timestamp="$(date "+%Y-%m-%dT%H:%M:%S%z")"
  local filename="$(echo -n "${timestamp}" | perl -pe "s/^(.+)T(\d{2}:\d{2}:\d{2})\+\d{4}$/\\1-\\2/" | tr -d ":").md"
  local post="content/posts/${filename}"

  echo "---"                >> "${post}"
  echo "title: \"XXX\""     >> "${post}"
  echo "date: ${timestamp}" >> "${post}"
  echo "tags: [\"\"]"       >> "${post}"
  echo "---"                >> "${post}"

  echo "${post} was created"
}

main "$@"
